version: "3"

services:
 
  # admin-ui:
  #   image: nginx:1.19.0-alpine
  #   restart: always
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=nginx"
  #     # - "traefik.frontend.rule=Host:xyz.co;PathPrefix:/static"
  #     - "traefik.port=80"
  #   volumes:
  #     - ./admin-ui/nginx.conf:/etc/nginx/nginx.conf
  #     - ./admin-ui/dist:/usr/share/nginx/html:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - NGINX_PORT=80
  #     - TZ=Asia/Shanghai
  #   ports:
  #     - 6888:80/tcp
  #   networks:
  #     apisix:
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"
  
  # browser:
  #   image: nginx:1.19.0-alpine
  #   restart: always
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=nginx"
  #     # - "traefik.frontend.rule=Host:xyz.co;PathPrefix:/static"
  #     - "traefik.port=80"
  #   volumes:
  #     - ./browser/nginx.conf:/etc/nginx/nginx.conf
  #     - ./browser/build:/usr/share/nginx/html:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - NGINX_PORT=80
  #     - TZ=Asia/Shanghai
  #   networks:
  #     apisix:
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "500m"

  factoryJob:
    image: mephostopilis/fswap:1.0.1
    restart: always
    ports:
      - 8052:8052
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./factoryJob/data:/opt/factoryJob/data
      - ./factoryJob/configs:/opt/factoryJob/configs
    command: ["java", "-jar", "/app/factoryJob.jar"]
    networks:
      apisix:
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    environment:
      - TZ=Asia/Shanghai

  pairJob:
    image: mephostopilis/fswap:1.0.1
    restart: always
    ports:
      - 8051:8051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pairJob/data:/opt/pairJob/data
      - ./pairJob/configs:/opt/pairJob/configs
    command: ["java", "-jar", "/app/pairJob.jar"]
    networks:
      apisix:
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    environment:
      - TZ=Asia/Shanghai
  
networks:
  apisix:
    driver: bridge
